apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-secret-pkcs12 # Name of custom resource 
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-project-pkcs12-token # Name of Kubernetes service token secret from previous step
  managedSecret:
    name: doppler-pkcs12  # Name of Kubernetes secret Operator will sync secrets to
    namespace: default # Namespace of the deployment that will use the secret
  processors:
    PKCS12_CERT:
      type: base64 # Instructs the Operator to not base64 encode the secret value again